# Generated by Django 3.1.4 on 2020-12-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
    ]
