# Generated by Django 3.1.4 on 2020-12-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201219_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='disc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
