# Generated by Django 3.1.4 on 2020-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201219_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='disc',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
